In [2]:
!pip install pandas numpy scikit-learn nltk joblib matplotlib

Requirement already satisfied: pandas in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (2.2.3)
Requirement already satisfied: numpy in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (2.2.2)
Requirement already satisfied: scikit-learn in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (1.6.1)
Requirement already satisfied: nltk in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (3.10.1)
Requirement already satisfied: joblib in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (1.4.2)
Requirement already satisfied: matplotlib in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (3.10.7)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2024.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: scipy>=1.6.0 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (1.15.1)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: defusedxml in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from nltk) (8.3.0)
Requirement already satisfied: regex>=2021.8.3 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from nltk) (2026.7.19)
Requirement already satisfied: tqdm in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from nltk) (4.70.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (24.2)
Requirement already satisfied: pillow>=8 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: colorama in c:\users\shiva\appdata\local\programs\python\python313\lib\site-packages (from click->nltk) (0.4.6)

[notice] A new release of pip is available: 24.3.1 -> 26.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

import joblib

print("All libraries imported successfully!")

All libraries imported successfully!

In [5]:
data = {
    "Comment": [
        "I love this phone",
        "Amazing product",
        "Very good quality",
        "Best purchase",
        "I am happy",

        "Worst phone",
        "Bad experience",
        "Very disappointing",
        "Waste of money",
        "I hate this",

        "It is okay",
        "Average product",
        "Nothing special",
        "Fine",
        "Normal"
    ],

    "Sentiment": [
        "Positive",
        "Positive",
        "Positive",
        "Positive",
        "Positive",

        "Negative",
        "Negative",
        "Negative",
        "Negative",
        "Negative",

        "Neutral",
        "Neutral",
        "Neutral",
        "Neutral",
        "Neutral"
    ]
}

df = pd.DataFrame(data)

df

               Comment Sentiment
0    I love this phone  Positive
1      Amazing product  Positive
2    Very good quality  Positive
3        Best purchase  Positive
4           I am happy  Positive
5          Worst phone  Negative
6       Bad experience  Negative
7   Very disappointing  Negative
8       Waste of money  Negative
9          I hate this  Negative
10          It is okay   Neutral
11     Average product   Neutral
12     Nothing special   Neutral
13                Fine   Neutral
14              Normal   Neutral

In [6]:
df.to_csv("dataset/train.csv", index=False)

print("Dataset saved successfully!")

Dataset saved successfully!

In [7]:
df = pd.read_csv("dataset/train.csv")

df.head()

             Comment Sentiment
0  I love this phone  Positive
1    Amazing product  Positive
2  Very good quality  Positive
3      Best purchase  Positive
4         I am happy  Positive

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Comment    15 non-null     object
 1   Sentiment  15 non-null     object
dtypes: object(2)
memory usage: 372.0+ bytes

In [9]:
X = df["Comment"]
y = df["Sentiment"]

print("Features:")
print(X.head())

print("\nLabels:")
print(y.head())

Features:
0    I love this phone
1      Amazing product
2    Very good quality
3        Best purchase
4           I am happy
Name: Comment, dtype: object

Labels:
0    Positive
1    Positive
2    Positive
3    Positive
4    Positive
Name: Sentiment, dtype: object

In [10]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("Training Data:", len(X_train))
print("Testing Data :", len(X_test))

Training Data: 12
Testing Data : 3

In [27]:
model = Pipeline([
    ("tfidf", TfidfVectorizer(ngram_range=(1,2))),
    ("classifier", LogisticRegression(max_iter=1000))
])

In [28]:
model.fit(X_train, y_train)

print("AI Model trained successfully!")

AI Model trained successfully!

In [29]:
predictions = model.predict(X_test)

print("Predictions:")
print(predictions)

Predictions:
['Neutral' 'Positive' 'Negative']

In [30]:
accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", accuracy)

Accuracy: 0.0

In [32]:
result = pd.DataFrame({
    "Actual": y_test.values,
    "Predicted": predictions
})

print(result)

     Actual Predicted
0  Negative   Neutral
1   Neutral  Positive
2  Positive  Negative

In [33]:
print(f"Accuracy: {accuracy*100:.2f}%")

Accuracy: 0.00%

In [22]:
print(model.predict(["I love this phone"]))

['Negative']

In [23]:
print(model.predict(["Worst phone ever"]))

['Negative']

In [24]:
print(model.predict(["It is okay"]))

['Neutral']

In [25]:
print(X_train)

13                  Fine
5            Worst phone
8         Waste of money
2      Very good quality
1        Amazing product
14                Normal
4             I am happy
7     Very disappointing
10            It is okay
12       Nothing special
3          Best purchase
6         Bad experience
Name: Comment, dtype: object

In [34]:
print(X_test)

9           I hate this
11      Average product
0     I love this phone
Name: Comment, dtype: object

In [35]:
vectorizer = model.named_steps["tfidf"]

print(vectorizer.get_feature_names_out())

['am' 'am happy' 'amazing' 'amazing product' 'bad' 'bad experience' 'best'
 'best purchase' 'disappointing' 'experience' 'fine' 'good' 'good quality'
 'happy' 'is' 'is okay' 'it' 'it is' 'money' 'normal' 'nothing'
 'nothing special' 'of' 'of money' 'okay' 'phone' 'product' 'purchase'
 'quality' 'special' 'very' 'very disappointing' 'very good' 'waste'
 'waste of' 'worst' 'worst phone']